### PR TITLE
[PE-D] Fix `lastContacted`

### LINKED ISSUE #178: [PE-D] "Contacted" [DATETIME] formatting of date time only works for 1 whitespace
Inputting a value for DATETIME only works when there is one whitespace between date and time

Two Whitespace:

One whitespace:
Before:

After:

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: AAlghrairy/ped#3

### LINKED ISSUE #204: [PE-D] Wrong invalid command message.
Steps to reproduce:

- `contacted INDEX dt/DATETIME`

Expected: Invalid command output.

Actual: Command usage for an irrelevant command, `addNote`.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: atmh/ped#9

### LINKED ISSUE #207: [PE-D] Invalid dates not handled for contacted.
Steps to reproduce:
- `contacted 1 dt/31-02-2021 00:00`

Expected: Command rejected.

Actual: Command executes successfully.

Reasoning: 31st February do not exist.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: atmh/ped#11

### LINKED ISSUE #224: [PE-D] Last contacted date can be set to the future
Steps to reproduce:
- `contacted 1 dt/21-03-3000 21:03`

Expected: Contacted date in the future should not be allowed and command should be rejected.

Actual: Command executes successfully.

Reasoning: Does contacted date being in the future make sense?

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: atmh/ped#16

### PR DESCRIPTION
**Pull request by sheimoria**
### Changes

- [x] Fix `contacted` command accepting invalid dates such as `31/02/2022 21:03`, closes #207 
- [x] Fix `contacted` command showing wrong invalid format message, closes #204 
- [x] Fix `contacted` command not accepting >1 whitespace in-between date and time, closes #178 
- [x] Fix `contacted` and `updateClient` command allowing future date times for `lastContacted`, closes #224

### CODE REVIEW

File: src/main/java/seedu/address/model/client/DateTime.java [hunk 1]
```diff
@@ -44,6 +49,14 @@ public static boolean isValidDateTime(String test) {
         return test.matches(VALIDATION_REGEX);
     }
 
+    /**
+     * Returns true if a given string is a past datetime.
+     */
```
Comment (joelwongjy) [inline src/main/java/seedu/address/model/client/DateTime.java:54]: Good job creating a method for this!

**Review by joelwongjy — APPROVED** [review]
LGTM
