### PR TITLE
Add `clientCount` and `sortCriteria` to `ClientListPanel` and fix `ClientDisplay` not updating on edit client

### LINKED ISSUE #131: Fix client details not updating upon edit
Client details on the right panel are not updated when user updates client details.

### LINKED ISSUE #144: Add UI feedback for client list
- [ ] Display number of clients in client list
- [ ] Display current sorting method

### PR DESCRIPTION
**Pull request by joelwongjy**
Closes #144 and fixes #131.

### Issues
- UI does not display total client count and the current sort criteria.
- Client details not updated upon edit.
- Last contacted text on `ClientListCard` is not aligned.

### Changes
- Add methods to `MainWindow` and `ClientListPanel` to update client count and sort criteria upon add and sort.
- Add an enum for `SortCriteria` and modify `CommandResult` to access `sortCriteria`.
- Modify `SortCommand` to sort by default ordering on empty sort attribute.
- Modify `Logic`, `Model` and `CommandResult` to check index of client being updated.
- Modify `MainWindow` to update `ClientDisplay` upon updating of client.
- Fix padding issues on `ClientListCard`.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/CommandResult.java [hunk 1]
```diff
@@ -29,16 +30,19 @@
     private final boolean showClients;
 
     /** Clients should be sorted **/
-    private final boolean sortClients;
+    private final SortCriteria sortClients;
```
Comment (raynerljm) [inline src/main/java/seedu/address/logic/commands/CommandResult.java:33]: Great idea to use enums!

File: src/main/java/seedu/address/logic/commands/SortCommand.java [hunk 2]
```diff
@@ -30,7 +32,8 @@
             + PREFIX_SORT_DIRECTION + "desc";
 
     public static final String MESSAGE_SUCCESS = "Successfully sorted";
-    public static final String MESSAGE_INVALID_ATTRIBUTE = "This attribute is invalid";
+    public static final String MESSAGE_INVALID_ATTRIBUTE = "This attribute is invalid.\nThe available attributes are"
+            + " empty (default), numPolicies, premium and lastContacted.";
```
Comment (raynerljm) [inline src/main/java/seedu/address/logic/commands/SortCommand.java:36]: Minor nitpick but maybe you could wrap the enum values with an apostrophe or backtick to make it clear what the possible inputs are?

File: src/main/java/seedu/address/logic/commands/SortCommand.java [hunk 3]
```diff
@@ -54,26 +57,34 @@ public SortCommand(String attribute, boolean isAscending) {
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
         Comparator<Client> comparator;
+        SortCriteria criteria;
+        if (!Objects.equals(attribute, "") && !SortCriteria.isValidEnum(attribute)) {
```
Comment (raynerljm) [inline src/main/java/seedu/address/logic/commands/SortCommand.java:61]: Should this be an or instead of an and?

**Review by raynerljm — COMMENTED** [review]
Seems mostly alright except some few comments. After that, feel free to merge!

File: src/main/java/seedu/address/logic/commands/CommandResult.java (hunk 1 above)
Comment (joelwongjy) [reply src/main/java/seedu/address/logic/commands/CommandResult.java:33]: Thank you! :)

File: src/main/java/seedu/address/logic/commands/SortCommand.java (hunk 3 above)
Comment (joelwongjy) [reply src/main/java/seedu/address/logic/commands/SortCommand.java:61]: Should be && because I attribute being empty is valid (it will sort by default). So I only want to check for when attribute is not empty and not a sortcrtieria.

File: src/main/java/seedu/address/logic/commands/SortCommand.java (hunk 2 above)
Comment (joelwongjy) [reply src/main/java/seedu/address/logic/commands/SortCommand.java]: Good suggestion will do this!
