### PR TITLE
Fix invalid `birthday`s

### LINKED ISSUE #261: `birthday` accepts invalid dates
- Invalid dates e.g. `31-02-2022`
- Future dates e.g. `21-03-2032`

### PR DESCRIPTION
**Pull request by sheimoria**
### Changes

Closes #261 

- [x] Fix `addClient` and `updateClient` commands accepting future `birthday`s e.g. `21-03-2032`
- [x] Fix `addClient` and `updateClient` commands accepting invalid `birthday`s e.g. `31-04-2021` and `29-02-2022`

### CODE REVIEW

File: src/main/java/seedu/address/model/client/Date.java [hunk 1]
```diff
@@ -44,16 +48,21 @@ public static boolean isValidDate(String test) {
         return test.matches(VALIDATION_REGEX);
     }
 
-    @Override
-    public String toString() {
-        return value;
+    /**
+     * Returns true if a given string is a past datetime.
```
Comment (sheimoria) [inline src/main/java/seedu/address/model/client/Date.java:52]:
```suggestion
     * Returns true if a given string is a past date.
```

**Review by joelwongjy — APPROVED** [review]
LGTM!
